version: '2'
services:

  mongodb:
    image: "mongo:latest@sha256:593a394e77cab35eee83404d51f9297339ce11e05bea6285e3e9688a97a9708b"
    container_name: mongodb
    environment:
      - DOCKER_LABELS=true
    ports:
      - "27017:27017"
    expose:
      - 27017

  rabbitmq:
    image: sammlerio/rabbitmq:latest@sha256:dca80a30a4d219dc30468db1260d4b3d8227be9b8995a7e81d2b43ae72b9a494
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    logging:
      driver: none

#  scheduler-service:
#    image: sammlerio/scheduler-service
#    container_name: scheduler-service
#    environment:
#      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
#      - LOAD_JOBS_FROM_FILE=true
#    command: ["npm", "run", "start:watch"]
#    volumes:
#      - ./node_modules/scheduler-service:/opt/scheduler-service
#      - ./configs/scheduler-service/jobs:/opt/scheduler-service/src/config/jobs

